# Generated by Django 5.1.6 on 2025-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.CharField(default=' ', max_length=400),
        ),
    ]
