# Generated by Django 5.1.6 on 2025-03-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(default=' ', max_length=400),
        ),
    ]
