# Generated by Django 5.1.6 on 2025-03-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_rename_description_module_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course_description',
        ),
        migrations.AddField(
            model_name='module',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
