# Generated by Django 5.1.6 on 2025-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_alter_module_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='notes',
            field=models.URLField(blank=True, help_text='URL to the notes Folder on OneDrive', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='textbook',
            field=models.URLField(blank=True, help_text='URL to the textbook PDF on OneDrive', max_length=500, null=True),
        ),
    ]
