# Generated by Django 5.1.6 on 2025-03-05 11:37

import django.core.validators
import django.db.models.deletion
import modules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Level 1, Level 2', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('course_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('textbook', models.FileField(blank=True, null=True, upload_to='textbooks/', validators=[modules.models.validate_pdf_file])),
                ('notes', models.FileField(blank=True, null=True, upload_to='notes/', validators=[modules.models.validate_pdf_file])),
                ('difficulty_level', models.IntegerField(default=0, help_text='Difficulty from 0 to 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='modules.level')),
            ],
        ),
    ]
