# Generated by Django 5.1.6 on 2025-03-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_module_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='description',
            new_name='course_description',
        ),
    ]
